In [8]:
from kdm.models import KDMSequentialJointClassModel
import kdm
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_moons
import matplotlib.pyplot as plt
import numpy as np
from keras import metrics
from keras import losses
from keras import optimizers
from keras.models import Model
from keras.layers import Input, Dense
import keras
from pandas import read_csv, DataFrame
import os
os.environ["KERAS_BACKEND"] = "tensorflow"


In [9]:
df = read_csv('iris.csv')

In [10]:
df.head()

sepal length  sepal width  petal length  petal width         type
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [11]:
df['type'] = df['type'].apply(lambda x: [1,0,0] if x == 'Iris-setosa' else [0,1,0] if x == 'Iris-versicolor' else [0,0,1])

In [12]:
df.tail()

sepal length  sepal width  petal length  petal width       type
145           6.7          3.0           5.2          2.3  [0, 0, 1]
146           6.3          2.5           5.0          1.9  [0, 0, 1]
147           6.5          3.0           5.2          2.0  [0, 0, 1]
148           6.2          3.4           5.4          2.3  [0, 0, 1]
149           5.9          3.0           5.1          1.8  [0, 0, 1]

In [13]:

encoded_size = 4
dim_y = 3
encoder = keras.layers.Identity()
n_comp = 150
sequences = [
    {
        'type': 'merge'
    }]
kdm_model = KDMSequentialJointClassModel(encoded_size=encoded_size,
                                         dim_y=dim_y,
                                         encoder=encoder,
                                         n_comp=n_comp,
                                         sequences=sequences,
                                         sigma=0.5)

In [14]:
kdm_model.compile(optimizer=optimizers.Adam(learning_rate=5e-5),
                  loss=losses.sparse_categorical_crossentropy,
                  metrics=[metrics.sparse_categorical_accuracy])

In [15]:
data = []
for row in df.iterrows():
    y = row[1]['type']
    x = [row[1]['sepal length'], row[1]['sepal width'], row[1]['petal length'], row[1]['petal width']]
    data.append((x, y))
    

In [16]:
data

[([5.1, 3.5, 1.4, 0.2], [1, 0, 0]),
 ([4.9, 3.0, 1.4, 0.2], [1, 0, 0]),
 ([4.7, 3.2, 1.3, 0.2], [1, 0, 0]),
 ([4.6, 3.1, 1.5, 0.2], [1, 0, 0]),
 ([5.0, 3.6, 1.4, 0.2], [1, 0, 0]),
 ([5.4, 3.9, 1.7, 0.4], [1, 0, 0]),
 ([4.6, 3.4, 1.4, 0.3], [1, 0, 0]),
 ([5.0, 3.4, 1.5, 0.2], [1, 0, 0]),
 ([4.4, 2.9, 1.4, 0.2], [1, 0, 0]),
 ([4.9, 3.1, 1.5, 0.1], [1, 0, 0]),
 ([5.4, 3.7, 1.5, 0.2], [1, 0, 0]),
 ([4.8, 3.4, 1.6, 0.2], [1, 0, 0]),
 ([4.8, 3.0, 1.4, 0.1], [1, 0, 0]),
 ([4.3, 3.0, 1.1, 0.1], [1, 0, 0]),
 ([5.8, 4.0, 1.2, 0.2], [1, 0, 0]),
 ([5.7, 4.4, 1.5, 0.4], [1, 0, 0]),
 ([5.4, 3.9, 1.3, 0.4], [1, 0, 0]),
 ([5.1, 3.5, 1.4, 0.3], [1, 0, 0]),
 ([5.7, 3.8, 1.7, 0.3], [1, 0, 0]),
 ([5.1, 3.8, 1.5, 0.3], [1, 0, 0]),
 ([5.4, 3.4, 1.7, 0.2], [1, 0, 0]),
 ([5.1, 3.7, 1.5, 0.4], [1, 0, 0]),
 ([4.6, 3.6, 1.0, 0.2], [1, 0, 0]),
 ([5.1, 3.3, 1.7, 0.5], [1, 0, 0]),
 ([4.8, 3.4, 1.9, 0.2], [1, 0, 0]),
 ([5.0, 3.0, 1.6, 0.2], [1, 0, 0]),
 ([5.0, 3.4, 1.6, 0.4], [1, 0, 0]),
 ([5.2, 3.5, 1.5, 0.2], [1, 

In [17]:
input = np.array([x for x, y in data])
output = np.array([y for x, y in data])
y_out = np.array([int(np.argmax(y)) for y in output])

In [18]:
kdm_model.init_components(np.array(input), np.array(output),
                                init_sigma=True, sigma_mult=0.5, super_index=0, index=0)

In [19]:
y_out

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
input

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
check_1 = kdm_model.evaluate(np.array(input), np.array(y_out))


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1650 - sparse_categorical_accuracy: 0.9618  


In [22]:

print('Full Dataset loss:', check_1[0])
print('Full Dataset accuracy:', check_1[1])

Full Dataset loss: 0.24461616575717926
Full Dataset accuracy: 0.9399999976158142


## Training Power

In [23]:

encoded_size = 4
dim_y = 3
encoder = keras.layers.Identity()
n_comp = 150
sequences = [
    {
        'type': 'merge'
    }]
kdm_model = KDMSequentialJointClassModel(encoded_size=encoded_size,
                                         dim_y=dim_y,
                                         encoder=encoder,
                                         n_comp=n_comp,
                                         sequences=sequences,
                                         sigma=0.5)

In [24]:
kdm_model.compile(optimizer=optimizers.Adam(learning_rate=5e-5),
                  loss=losses.sparse_categorical_crossentropy,
                  metrics=[metrics.sparse_categorical_accuracy])

In [25]:
combined_y = np.array([[int(np.argmax(y)), y] for y in output])

/var/folders/2s/yq898nms72b5qxqbwz_hx8j80000gn/T/ipykernel_75571/2480946680.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  combined_y = np.array([[int(np.argmax(y)), y] for y in output])


In [26]:
combined_y

array([[0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0, array([1, 0, 0])],
       [0,

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    input, combined_y, test_size=0.4, random_state=42)

In [28]:
print(len(X_train))
len(X_test)

90


60

In [40]:

encoded_size = 4
dim_y = 3
encoder = keras.layers.Identity()
n_comp = 90
sequences = [
    {
        'type': 'merge'
    }]
kdm_model = KDMSequentialJointClassModel(encoded_size=encoded_size,
                                         dim_y=dim_y,
                                         encoder=encoder,
                                         n_comp=n_comp,
                                         sequences=sequences,
                                         sigma=0.5)

In [41]:
from tensorflow.keras import optimizers, losses

kdm_model.compile(optimizer=optimizers.Adam(learning_rate=5e-5),
              loss=losses.sparse_categorical_crossentropy,
              metrics=[metrics.sparse_categorical_accuracy,])


In [42]:
real_out = np.array([y[1] for y in y_train])

kdm_model.init_components(np.array(X_train), np.array(real_out),
                                init_sigma=True, sigma_mult=0.5, super_index=0, index=0)

In [43]:
history = kdm_model.fit(
    np.array(X_train),  # Your training data
    np.array(y_out),  # Your training labels
    batch_size=2,
    
    epochs=100, 
    verbose=1,  # Detailed logging
    validation_split=0.1,  # Explicit validation data
    shuffle=True  # Shuffle the data
)

Epoch 1/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3.8387 - sparse_categorical_accuracy: 0.3551 - val_loss: 1.5740 - val_sparse_categorical_accuracy: 0.5556
Epoch 2/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - loss: 4.1469 - sparse_categorical_accuracy: 0.4168 - val_loss: 1.5217 - val_sparse_categorical_accuracy: 0.6667
Epoch 3/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - loss: 3.4807 - sparse_categorical_accuracy: 0.3791 - val_loss: 1.4688 - val_sparse_categorical_accuracy: 0.6667
Epoch 4/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step - loss: 3.2106 - sparse_categorical_accuracy: 0.4794 - val_loss: 1.3955 - val_sparse_categorical_accuracy: 0.6667
Epoch 5/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 702us/step - loss: 3.2711 - sparse_categorical_accuracy: 0.4910 - val_loss: 1.3055 - val_sparse_categorical_accuracy: 0.6667
Epoch 6/100
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step - loss: 3.3081 - sparse_categorical_accuracy: 0.5048 - val_loss: 1.1989 - val_sparse_categorical_accuracy: 0.7778


In [44]:
print('Full Dataset loss:', check_full[0])
print('Full Dataset accuracy:', check_full[1])

Full Dataset loss: 1.0986123085021973
Full Dataset accuracy: 0.3333333432674408


In [45]:
y_out_test = np.array([y[0] for y in y_test])

In [46]:
check_test = kdm_model.evaluate(np.array(X_test), np.array(y_out_test))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4886 - sparse_categorical_accuracy: 0.6958 


In [47]:
print('Test Dataset loss:', check_test[0])
print('Test Dataset accuracy:', check_test[1])

Test Dataset loss: 0.4968946874141693
Test Dataset accuracy: 0.699999988079071
